export default [
  {
    name: "Song Lyrics Generator",
    desc: "Create unique song lyrics based on your theme and genre preferences.",
    category: "Music",
    icon: "https://cdn-icons-png.flaticon.com/128/3659/3659784.png",
    aiPrompt:
      "Write song lyrics in the specified genre, incorporating the given theme and mood. Include verses, chorus, and bridge structure. Consider the emotional impact and musical flow.",
    slug: "generate-lyrics",
    form: [
      {
        label: "Enter song theme/topic",
        field: "input",
        name: "theme",
        required: true,
      },
      {
        label: "Choose genre",
        field: "dropdown",
        name: "genre",
        required: true,
        options: [
          "Rock",
          "Pop",
          "Hip Hop",
          "R&B",
          "Country",
          "Folk",
          "Metal",
          "Jazz",
          "Blues",
          "Electronic",
        ],
      },
      {
        label: "Describe the mood/emotion",
        field: "input",
        name: "mood",
        required: true,
      },
      {
        label: "Additional notes (optional)",
        field: "textarea",
        name: "notes",
      },
    ],
  },
  {
    name: "Chord Progression Generator",
    desc: "Generate musical chord progressions based on genre and mood.",
    category: "Music",
    icon: "https://cdn-icons-png.flaticon.com/128/7634/7634542.png",
    aiPrompt:
      "Create a chord progression suitable for the specified genre and mood. Include both the basic progression and possible variations. Consider common patterns in the selected genre. Include a repeated bar section in the timeline of the song",
    slug: "chord-progression",
    form: [
      {
        label: "Choose genre",
        field: "dropdown",
        name: "genre",
        required: true,
        options: [
          "Rock",
          "Pop",
          "Jazz",
          "Blues",
          "Classical",
          "Folk",
          "R&B",
          "Electronic",
        ],
      },
      {
        label: "Desired mood",
        field: "input",
        name: "mood",
        required: true,
      },
      {
        label: "Key (optional)",
        field: "input",
        name: "key",
      },
    ],
  },
  {
    name: "Song Structure Planner",
    desc: "Plan your song's structure and arrangement.",
    category: "Music",
    icon: "https://cdn-icons-png.flaticon.com/128/2907/2907253.png",
    aiPrompt:
      "Create a detailed song structure including arrangement suggestions, section lengths, and dynamic changes based on the genre and style preferences.",
    slug: "song-structure",
    form: [
      {
        label: "Choose genre",
        field: "dropdown",
        name: "genre",
        required: true,
        options: [
          "Rock",
          "Pop",
          "Hip Hop",
          "Electronic",
          "Jazz",
          "Folk",
          "Metal",
          "Country",
        ],
      },
      {
        label: "Song length (minutes)",
        field: "input",
        name: "length",
        required: true,
      },
      {
        label: "Style reference (optional)",
        field: "input",
        name: "reference",
      },
    ],
  },
  {
    name: "Band Bio Generator",
    desc: "Create professional band biographies for promotional materials.",
    category: "Music",
    icon: "https://cdn-icons-png.flaticon.com/128/3994/3994407.png",
    aiPrompt:
      "Write a compelling band biography incorporating the band's history, style, influences, and achievements. Make it engaging and suitable for promotional use.",
    slug: "band-bio",
    form: [
      {
        label: "Band name",
        field: "input",
        name: "bandName",
        required: true,
      },
      {
        label: "Genre(s)",
        field: "input",
        name: "genres",
        required: true,
      },
      {
        label: "Key achievements",
        field: "textarea",
        name: "achievements",
      },
      {
        label: "Musical influences",
        field: "textarea",
        name: "influences",
      },
    ],
  },
  {
    name: "Music Marketing Copy",
    desc: "Generate promotional copy for music releases and events.",
    category: "Music",
    icon: "https://cdn-icons-png.flaticon.com/128/3039/3039386.png",
    aiPrompt:
      "Create engaging promotional copy for the specified music release or event. Include key selling points, mood, and call to action.",
    slug: "music-marketing",
    form: [
      {
        label: "Choose project type",
        field: "dropdown",
        name: "projectType",
        required: true,
        options: [
          "Single Release",
          "Album Release",
          "Music Video",
          "Concert",
          "Tour",
          "Festival Appearance",
        ],
      },
      {
        label: "Project name",
        field: "input",
        name: "projectName",
        required: true,
      },
      {
        label: "Key details",
        field: "textarea",
        name: "details",
        required: true,
      },
      {
        label: "Target audience",
        field: "input",
        name: "audience",
      },
    ],
  },
  {
    name: "YouTube Tags Generator",
    desc: "Generate the best YouTube tags to improve video discoverability.",
    category: "YouTube",
    icon: "https://cdn-icons-png.flaticon.com/128/6062/6062642.png",
    aiPrompt:
      "Generate a list of the best SEO-friendly YouTube tags based on the given video topic.",
    slug: "youtube-tags",
    form: [
      {
        label: "Enter video topic",
        field: "input",
        name: "title",
        required: true,
      },
      {
        label: "Enter Youtube Video Outline Here (optional)",
        field: "textarea",
        name: "outline",
      },
    ],
  },
  {
    name: "Blog Title",
    desc: "An AI tool that generates blog titles based on your blog information.",
    category: "Blog",
    icon: "https://cdn-icons-png.flaticon.com/128/16901/16901535.png",
    aiPrompt:
      "Give me 5 blog titles based on the given niche and outline in a bullet format.",
    slug: "generate-blog-title",
    form: [
      {
        label: "Enter your blog niche",
        field: "input",
        name: "niche",
        required: true,
      },
      {
        label: "Enter blog outline",
        field: "textarea",
        name: "outline",
      },
    ],
  },
  {
    name: "Career Path Planner",
    desc: "Get personalized career path recommendations based on your interests and goals.",
    category: "Career",
    icon: "https://cdn-icons-png.flaticon.com/128/1584/1584733.png",
    aiPrompt:
      "Based on the provided interests, skills, and preferences, recommend specific career paths, required qualifications, and job market outlook. Include salary ranges, growth potential, and recommended steps to enter the field.",
    slug: "career-path",
    form: [
      {
        label: "Choose field of interest",
        field: "dropdown",
        name: "field",
        required: true,
        options: [
          "Technology",
          "Healthcare",
          "Finance",
          "Education",
          "Engineering",
          "Creative Arts",
          "Business",
          "Science",
          "Trades",
          "Legal",
        ],
      },
      {
        label: "Current education level",
        field: "dropdown",
        name: "education",
        required: true,
        options: [
          "High School",
          "Some College",
          "Associate's Degree",
          "Bachelor's Degree",
          "Master's Degree",
          "PhD",
          "Trade School",
          "Self-Taught",
        ],
      },
      {
        label: "Key skills (separate with commas)",
        field: "input",
        name: "skills",
        required: true,
      },
      {
        label: "Preferred work environment",
        field: "dropdown",
        name: "environment",
        options: [
          "Office",
          "Remote",
          "Hybrid",
          "Outdoor",
          "Laboratory",
          "Studio",
          "Multiple Locations",
        ],
      },
    ],
  },
  {
    name: "Course Recommendation",
    desc: "Find the most valuable and recognized courses for your chosen career path.",
    category: "Education",
    icon: "https://cdn-icons-png.flaticon.com/128/2436/2436683.png",
    aiPrompt:
      "Recommend specific courses, certifications, and educational programs based on the career goal. Include information about accreditation, industry recognition, job placement rates, and return on investment.",
    slug: "course-finder",
    form: [
      {
        label: "Choose target career",
        field: "dropdown",
        name: "career",
        required: true,
        options: [
          "Software Developer",
          "Data Scientist",
          "Digital Marketing",
          "Project Management",
          "Cybersecurity",
          "Healthcare Professional",
          "Financial Analyst",
          "UX/UI Designer",
          "Business Administrator",
          "Teacher/Educator",
        ],
      },
      {
        label: "Budget range",
        field: "dropdown",
        name: "budget",
        required: true,
        options: [
          "Under $1,000",
          "$1,000 - $5,000",
          "$5,000 - $15,000",
          "$15,000 - $30,000",
          "$30,000+",
        ],
      },
      {
        label: "Preferred duration",
        field: "dropdown",
        name: "duration",
        required: true,
        options: [
          "0-3 months",
          "3-6 months",
          "6-12 months",
          "1-2 years",
          "2-4 years",
          "4+ years",
        ],
      },
      {
        label: "Learning format preference",
        field: "dropdown",
        name: "format",
        options: [
          "Online Self-Paced",
          "Online Instructor-Led",
          "In-Person",
          "Hybrid",
          "Bootcamp",
          "Traditional University",
        ],
      },
    ],
  },
  {
    name: "Recipe Creator",
    desc: "Generate unique recipes based on your ingredients, dietary preferences, and cuisine type.",
    category: "Cooking",
    icon: "https://cdn-icons-png.flaticon.com/128/2921/2921822.png",
    aiPrompt:
      "Create a detailed recipe including ingredients, instructions, nutritional information, and cooking tips based on the specified parameters. Include preparation time, cooking time, and serving suggestions.",
    slug: "recipe-creator",
    form: [
      {
        label: "Choose cuisine type",
        field: "dropdown",
        name: "cuisine",
        required: true,
        options: [
          "Italian",
          "Mexican",
          "Asian",
          "Mediterranean",
          "Indian",
          "American",
          "French",
          "Middle Eastern",
          "Thai",
          "Japanese",
        ],
      },
      {
        label: "Dietary restrictions",
        field: "dropdown",
        name: "diet",
        required: true,
        options: [
          "None",
          "Vegetarian",
          "Vegan",
          "Gluten-Free",
          "Keto",
          "Low-Carb",
          "Dairy-Free",
          "Paleo",
          "Low-Calorie",
          "High-Protein",
        ],
      },
      {
        label: "Main ingredients (separate with commas)",
        field: "input",
        name: "ingredients",
        required: true,
      },
      {
        label: "Cooking skill level",
        field: "dropdown",
        name: "skillLevel",
        options: ["Beginner", "Intermediate", "Advanced", "Chef"],
      },
      {
        label: "Maximum cooking time (minutes)",
        field: "input",
        name: "maxTime",
      },
    ],
  },
  {
    name: "Meal Plan Generator",
    desc: "Create personalized meal plans based on your dietary goals and preferences.",
    category: "Cooking",
    icon: "https://cdn-icons-png.flaticon.com/128/1830/1830839.png",
    aiPrompt:
      "Generate a weekly meal plan including breakfast, lunch, dinner, and snacks. Include shopping list, prep instructions, and nutritional breakdown.",
    slug: "meal-plan",
    form: [
      {
        label: "Number of days",
        field: "dropdown",
        name: "days",
        required: true,
        options: ["1 day", "3 days", "5 days", "7 days", "14 days", "30 days"],
      },
      {
        label: "Daily calorie target",
        field: "dropdown",
        name: "calories",
        required: true,
        options: [
          "1200-1500",
          "1500-1800",
          "1800-2100",
          "2100-2400",
          "2400-2700",
          "2700+",
        ],
      },
      {
        label: "Dietary preferences",
        field: "dropdown",
        name: "dietType",
        required: true,
        options: [
          "No Restrictions",
          "Vegetarian",
          "Vegan",
          "Paleo",
          "Keto",
          "Mediterranean",
          "Low-Carb",
          "High-Protein",
        ],
      },
      {
        label: "Cooking time per meal (minutes)",
        field: "dropdown",
        name: "cookingTime",
        options: ["Under 15", "15-30", "30-45", "45-60", "60+"],
      },
    ],
  },
  {
    name: "Vacation Planner",
    desc: "Create a customized vacation itinerary based on your preferences and budget.",
    category: "Travel",
    icon: "https://cdn-icons-png.flaticon.com/128/2200/2200326.png",
    aiPrompt:
      "Generate a detailed vacation plan including destinations, activities, accommodations, and travel logistics based on the specified parameters. Include budget breakdown and timing recommendations.",
    slug: "vacation-plan",
    form: [
      {
        label: "Choose destination type",
        field: "dropdown",
        name: "destinationType",
        required: true,
        options: [
          "Beach Resort",
          "City Break",
          "Mountain/Hiking",
          "Cultural Tour",
          "Adventure Trip",
          "Rural/Countryside",
          "Island Hopping",
          "Cruise",
          "Wildlife Safari",
          "Theme Parks",
        ],
      },
      {
        label: "Trip duration (days)",
        field: "dropdown",
        name: "duration",
        required: true,
        options: [
          "Weekend (2-3)",
          "Short Break (4-5)",
          "Week (6-8)",
          "Extended (9-14)",
          "Long Trip (15+)",
        ],
      },
      {
        label: "Daily budget per person",
        field: "dropdown",
        name: "budget",
        required: true,
        options: [
          "Budget ($50-100)",
          "Moderate ($100-200)",
          "Comfort ($200-350)",
          "Luxury ($350-500)",
          "Ultra-Luxury ($500+)",
        ],
      },
      {
        label: "Travel style",
        field: "dropdown",
        name: "travelStyle",
        options: ["Relaxed", "Moderate", "Active", "Fast-Paced", "Mixed"],
      },
      {
        label: "Special interests/requirements",
        field: "textarea",
        name: "interests",
      },
    ],
  },
  {
    name: "Travel Budget Calculator",
    desc: "Calculate detailed travel costs and create a comprehensive budget plan.",
    category: "Travel",
    icon: "https://cdn-icons-png.flaticon.com/128/2942/2942544.png",
    aiPrompt:
      "Create a detailed travel budget breakdown including transportation, accommodation, activities, food, and miscellaneous expenses. Provide money-saving tips and contingency recommendations.",
    slug: "travel-budget",
    form: [
      {
        label: "Choose destination",
        field: "dropdown",
        name: "destination",
        required: true,
        options: [
          "Western Europe",
          "Eastern Europe",
          "North America",
          "South America",
          "Southeast Asia",
          "East Asia",
          "Middle East",
          "Africa",
          "Australia/NZ",
          "Caribbean",
        ],
      },
      {
        label: "Number of travelers",
        field: "input",
        name: "travelers",
        required: true,
      },
      {
        label: "Trip duration (days)",
        field: "input",
        name: "duration",
        required: true,
      },
      {
        label: "Travel style",
        field: "dropdown",
        name: "travelStyle",
        required: true,
        options: [
          "Budget Backpacker",
          "Mid-Range",
          "Comfort",
          "Luxury",
          "Ultra-Luxury",
        ],
      },
      {
        label: "Special activities/tours",
        field: "textarea",
        name: "activities",
      },
    ],
  },
  {
    name: "Local Food Explorer",
    desc: "Discover and learn about local specialties and food experiences in your destination.",
    category: "Travel",
    icon: "https://cdn-icons-png.flaticon.com/128/4080/4080032.png",
    aiPrompt:
      "Generate recommendations for local food experiences, including must-try dishes, best restaurants, food markets, and culinary activities. Include cultural context and dining etiquette tips.",
    slug: "food-explorer",
    form: [
      {
        label: "Choose destination",
        field: "dropdown",
        name: "destination",
        required: true,
        options: [
          "Italy",
          "Japan",
          "France",
          "Thailand",
          "Mexico",
          "India",
          "Spain",
          "Vietnam",
          "Greece",
          "Morocco",
        ],
      },
      {
        label: "Dietary restrictions",
        field: "dropdown",
        name: "diet",
        required: true,
        options: [
          "None",
          "Vegetarian",
          "Vegan",
          "Halal",
          "Kosher",
          "Gluten-Free",
          "Dairy-Free",
          "Pescatarian",
        ],
      },
      {
        label: "Spice preference",
        field: "dropdown",
        name: "spiceLevel",
        options: ["Mild", "Medium", "Spicy", "Very Spicy"],
      },
      {
        label: "Budget per meal",
        field: "dropdown",
        name: "mealBudget",
        options: [
          "Street Food ($)",
          "Casual ($$)",
          "Mid-Range ($$$)",
          "Fine Dining ($$$$)",
        ],
      },
    ],
  },
  {
    name: "Diet Plan Generator",
    desc: "Create a personalized diet plan based on your weight loss goals and preferences.",
    category: "Health",
    icon: "https://cdn-icons-png.flaticon.com/128/3373/3373108.png",
    aiPrompt:
      "Generate a detailed diet plan including meal suggestions, portion sizes, and nutritional breakdown. Include tips for meal prep, snack alternatives, and eating schedules based on the specified parameters.",
    slug: "diet-plan",
    form: [
      {
        label: "Current weight (kg)",
        field: "input",
        name: "currentWeight",
        required: true,
      },
      {
        label: "Target weight (kg)",
        field: "input",
        name: "targetWeight",
        required: true,
      },
      {
        label: "Choose diet type",
        field: "dropdown",
        name: "dietType",
        required: true,
        options: [
          "Balanced Calorie Deficit",
          "Low-Carb",
          "Keto",
          "Mediterranean",
          "Intermittent Fasting",
          "Plant-Based",
          "High-Protein",
          "Paleo",
          "DASH Diet",
          "Flexitarian",
        ],
      },
      {
        label: "Activity level",
        field: "dropdown",
        name: "activityLevel",
        required: true,
        options: [
          "Sedentary",
          "Lightly Active",
          "Moderately Active",
          "Very Active",
          "Extremely Active",
        ],
      },
      {
        label: "Food allergies/restrictions",
        field: "textarea",
        name: "restrictions",
      },
    ],
  },
  {
    name: "Weight Loss Calculator",
    desc: "Calculate your caloric needs and create a personalized weight loss timeline.",
    category: "Health",
    icon: "https://cdn-icons-png.flaticon.com/128/9583/9583436.png",
    aiPrompt:
      "Calculate daily caloric needs, create a sustainable deficit plan, and provide a realistic timeline for weight loss goals. Include maintenance strategies and milestone markers.",
    slug: "weight-loss-calculator",
    form: [
      {
        label: "Age",
        field: "input",
        name: "age",
        required: true,
      },
      {
        label: "Gender",
        field: "dropdown",
        name: "gender",
        required: true,
        options: ["Male", "Female", "Other"],
      },
      {
        label: "Height (cm)",
        field: "input",
        name: "height",
        required: true,
      },
      {
        label: "Weekly weight loss goal (kg)",
        field: "dropdown",
        name: "weeklyGoal",
        required: true,
        options: ["0.25 kg", "0.5 kg", "0.75 kg", "1.0 kg"],
      },
      {
        label: "Exercise frequency (days/week)",
        field: "dropdown",
        name: "exerciseFrequency",
        required: true,
        options: ["0-1", "2-3", "4-5", "6-7"],
      },
    ],
  },
  {
    name: "Meal Swap Suggestions",
    desc: "Get healthier alternatives to your favorite meals for weight loss.",
    category: "Health",
    icon: "https://cdn-icons-png.flaticon.com/128/1046/1046874.png",
    aiPrompt:
      "Suggest healthier alternatives to common meals and snacks, including nutritional comparisons and preparation instructions. Provide portion control guidance and flavor enhancement tips.",
    slug: "meal-swaps",
    form: [
      {
        label: "Choose meal type",
        field: "dropdown",
        name: "mealType",
        required: true,
        options: [
          "Breakfast",
          "Lunch",
          "Dinner",
          "Snacks",
          "Desserts",
          "Beverages",
        ],
      },
      {
        label: "Current favorite meals",
        field: "textarea",
        name: "currentMeals",
        required: true,
      },
      {
        label: "Calorie target per meal",
        field: "dropdown",
        name: "calorieTarget",
        required: true,
        options: ["Under 300", "300-400", "400-500", "500-600", "600+"],
      },
      {
        label: "Dietary preferences",
        field: "dropdown",
        name: "preferences",
        options: [
          "No Restrictions",
          "Low-Carb",
          "High-Protein",
          "Vegetarian",
          "Vegan",
          "Gluten-Free",
        ],
      },
    ],
  },
  {
    name: "Progress Tracker",
    desc: "Track your weight loss journey and get personalized adjustment recommendations.",
    category: "Health",
    icon: "https://cdn-icons-png.flaticon.com/128/9464/9464085.png",
    aiPrompt:
      "Create a progress tracking plan with metrics, milestone celebrations, and adjustment recommendations based on progress. Include troubleshooting tips for plateaus.",
    slug: "progress-tracker",
    form: [
      {
        label: "Starting date",
        field: "input",
        name: "startDate",
        required: true,
      },
      {
        label: "Initial weight (kg)",
        field: "input",
        name: "initialWeight",
        required: true,
      },
      {
        label: "Current weight (kg)",
        field: "input",
        name: "currentWeight",
        required: true,
      },
      {
        label: "Tracking frequency",
        field: "dropdown",
        name: "trackingFrequency",
        required: true,
        options: ["Daily", "Every 3 Days", "Weekly", "Bi-weekly", "Monthly"],
      },
      {
        label: "Measurements to track",
        field: "textarea",
        name: "measurements",
        placeholder: "e.g., waist, hips, chest, arms, thighs",
      },
    ],
  },
  {
    name: "Emotional Eating Guide",
    desc: "Get strategies to manage emotional eating and develop healthier habits.",
    category: "Health",
    icon: "https://cdn-icons-png.flaticon.com/128/4207/4207247.png",
    aiPrompt:
      "Create a personalized plan to address emotional eating triggers, including coping strategies, alternative activities, and mindful eating practices.",
    slug: "emotional-eating",
    form: [
      {
        label: "Common triggers",
        field: "dropdown",
        name: "triggers",
        required: true,
        options: [
          "Stress",
          "Boredom",
          "Anxiety",
          "Sadness",
          "Celebration",
          "Social Pressure",
          "Fatigue",
          "Mixed",
        ],
      },
      {
        label: "Typical craving types",
        field: "dropdown",
        name: "cravings",
        required: true,
        options: ["Sweet", "Salty", "Fatty", "Carbs", "Mixed"],
      },
      {
        label: "Time of day most affected",
        field: "dropdown",
        name: "timeOfDay",
        options: [
          "Morning",
          "Afternoon",
          "Evening",
          "Late Night",
          "Various Times",
        ],
      },
      {
        label: "Current coping methods",
        field: "textarea",
        name: "copingMethods",
      },
    ],
  },
  {
    name: "Business Idea Generator",
    desc: "Generate viable business ideas based on your interests, skills, and market opportunities.",
    category: "Business",
    icon: "https://cdn-icons-png.flaticon.com/128/1989/1989125.png",
    aiPrompt:
      "Generate specific business ideas based on the given parameters. Include market analysis, potential revenue streams, initial investment needed, and key steps to get started.",
    slug: "business-ideas",
    form: [
      {
        label: "Choose business type",
        field: "dropdown",
        name: "businessType",
        required: true,
        options: [
          "Online Business",
          "Local Service",
          "Retail Store",
          "Food & Beverage",
          "Consulting",
          "Manufacturing",
          "Technology",
          "Creative Services",
          "Education & Training",
          "Health & Wellness",
        ],
      },
      {
        label: "Initial investment range",
        field: "dropdown",
        name: "investment",
        required: true,
        options: [
          "Under $1,000",
          "$1,000 - $5,000",
          "$5,000 - $20,000",
          "$20,000 - $50,000",
          "$50,000+",
        ],
      },
      {
        label: "Your key skills",
        field: "textarea",
        name: "skills",
        required: true,
      },
      {
        label: "Target market location",
        field: "dropdown",
        name: "location",
        options: [
          "Local",
          "Regional",
          "National",
          "International",
          "Online Only",
        ],
      },
    ],
  },
  {
    name: "Business Plan Generator",
    desc: "Create a detailed business plan for your startup or small business.",
    category: "Business",
    icon: "https://cdn-icons-png.flaticon.com/128/1087/1087927.png",
    aiPrompt:
      "Generate a comprehensive business plan including market analysis, financial projections, marketing strategy, and operational plans based on the provided information.",
    slug: "business-plan",
    form: [
      {
        label: "Business name",
        field: "input",
        name: "businessName",
        required: true,
      },
      {
        label: "Choose industry",
        field: "dropdown",
        name: "industry",
        required: true,
        options: [
          "Retail",
          "E-commerce",
          "Technology",
          "Food Service",
          "Professional Services",
          "Healthcare",
          "Education",
          "Manufacturing",
          "Entertainment",
          "Real Estate",
        ],
      },
      {
        label: "Target market description",
        field: "textarea",
        name: "targetMarket",
        required: true,
      },
      {
        label: "Initial funding source",
        field: "dropdown",
        name: "funding",
        required: true,
        options: [
          "Personal Savings",
          "Bank Loan",
          "Investors",
          "Crowdfunding",
          "Family & Friends",
          "Bootstrap",
        ],
      },
      {
        label: "Competitive advantages",
        field: "textarea",
        name: "advantages",
        required: true,
      },
    ],
  },
  {
    name: "Side Hustle Finder",
    desc: "Discover profitable side hustle opportunities based on your schedule and skills.",
    category: "Business",
    icon: "https://cdn-icons-png.flaticon.com/128/2382/2382533.png",
    aiPrompt:
      "Recommend specific side hustle opportunities based on the given parameters. Include startup costs, potential earnings, time commitment, and step-by-step implementation plan.",
    slug: "side-hustle",
    form: [
      {
        label: "Available hours per week",
        field: "dropdown",
        name: "hours",
        required: true,
        options: [
          "0-5 hours",
          "5-10 hours",
          "10-20 hours",
          "20-30 hours",
          "30+ hours",
        ],
      },
      {
        label: "Choose preferred type",
        field: "dropdown",
        name: "hustleType",
        required: true,
        options: [
          "Online Freelancing",
          "Local Services",
          "Content Creation",
          "E-commerce",
          "Teaching/Tutoring",
          "Rental Business",
          "Digital Products",
          "Consulting",
        ],
      },
      {
        label: "Starting budget",
        field: "dropdown",
        name: "budget",
        required: true,
        options: [
          "No Budget",
          "Under $100",
          "$100 - $500",
          "$500 - $1,000",
          "$1,000+",
        ],
      },
      {
        label: "Key skills & resources",
        field: "textarea",
        name: "skills",
        required: true,
      },
    ],
  },
  {
    name: "Blog Content",
    desc: "Generate high-quality blog content based on a given topic and outline.",
    category: "Blog",
    icon: "https://cdn-icons-png.flaticon.com/128/4286/4286834.png",
    aiPrompt:
      "Write a detailed blog post based on the given topic and outline. Ensure it is engaging, informative, and well-structured.",
    slug: "generate-blog-content",
    form: [
      {
        label: "Enter your blog topic",
        field: "input",
        name: "topic",
        required: true,
      },
      {
        label: "Enter blog outline (optional)",
        field: "textarea",
        name: "outline",
      },
    ],
  },
  {
    name: "Blog Topic Ideas",
    desc: "Generate unique and trending blog topic ideas for your niche.",
    category: "Blog",
    icon: "https://cdn-icons-png.flaticon.com/128/5827/5827224.png",
    aiPrompt:
      "Generate 10 blog topic ideas based on the given niche. Format the result as a bullet list.",
    slug: "generate-blog-topic-ideas",
    form: [
      {
        label: "Enter your blog niche",
        field: "input",
        name: "niche",
        required: true,
      },
    ],
  },
  {
    name: "YouTube SEO Title",
    desc: "Generate an SEO-friendly YouTube video title to improve rankings.",
    category: "YouTube",
    icon: "https://cdn-icons-png.flaticon.com/128/1384/1384060.png",
    aiPrompt:
      "Generate 5 catchy, SEO-optimized YouTube video titles based on the given topic.",
    slug: "youtube-seo-title",
    form: [
      {
        label: "Enter video topic",
        field: "input",
        name: "videoTopic",
        required: true,
      },
    ],
  },
  {
    name: "YouTube Description",
    desc: "Generate an engaging and SEO-friendly YouTube video description.",
    category: "YouTube",
    icon: "https://cdn-icons-png.flaticon.com/128/1384/1384060.png",
    aiPrompt:
      "Write a detailed, SEO-optimized YouTube description based on the given video topic and keywords.",
    slug: "youtube-description",
    form: [
      {
        label: "Enter video topic",
        field: "input",
        name: "videoTopic",
        required: true,
      },
      {
        label: "Enter keywords (optional)",
        field: "input",
        name: "keywords",
      },
    ],
  },
  {
    name: "Add Emojis to Text",
    desc: "Enhance your text by automatically adding relevant emojis.",
    category: "Writing",
    icon: "https://cdn-icons-png.flaticon.com/128/616/616489.png",
    aiPrompt:
      "Add relevant emojis to the given text while keeping the meaning intact.",
    slug: "add-emojis-to-text",
    form: [
      {
        label: "Enter your text",
        field: "textarea",
        name: "text",
        required: true,
      },
    ],
  },
  {
    name: "Rewrite Article (Plagiarism-Free)",
    desc: "Rewrite any article to be unique, plagiarism-free, and well-structured.",
    category: "Writing",
    icon: "https://cdn-icons-png.flaticon.com/128/1532/1532556.png",
    aiPrompt:
      "Rewrite the given article to make it 100% unique, plagiarism-free, and well-structured.",
    slug: "rewrite-article",
    form: [
      {
        label: "Paste your article",
        field: "textarea",
        name: "article",
        required: true,
      },
    ],
  },

  {
    name: "Small Business Ideas Generator",
    desc: "Generate profitable small business ideas based on your interests and industry.",
    category: "Business",
    icon: "https://cdn-icons-png.flaticon.com/128/3125/3125713.png",
    aiPrompt:
      "Suggest 5 small business ideas based on the given interests and industry.",
    slug: "small-business-ideas",
    form: [
      {
        label: "Enter your interests",
        field: "input",
        name: "interests",
        required: true,
      },
      { label: "Enter industry (optional)", field: "input", name: "industry" },
    ],
  },
  {
    name: "Coding Project Ideas",
    desc: "Generate creative and practical coding project ideas.",
    category: "Coding",
    icon: "https://cdn-icons-png.flaticon.com/128/2721/2721275.png",
    aiPrompt:
      "Suggest 5 coding project ideas based on the given programming language and experience level.",
    slug: "coding-project-ideas",
    form: [
      {
        label: "Enter programming language",
        field: "input",
        name: "language",
        required: true,
      },
      {
        label: "Experience level",
        field: "dropdown",
        name: "experience",
        options: ["Beginner", "Intermediate", "Advanced"],
        required: true,
      },
    ],
  },

  // Development & Coding Tools
  {
    name: "Code Generator",
    desc: "Generate code snippets in different programming languages.",
    category: "Coding",
    icon: "https://cdn-icons-png.flaticon.com/128/742/742751.png",
    aiPrompt:
      "Generate a code snippet based on the given problem statement and programming language.",
    slug: "code-generator",
    form: [
      {
        label: "Enter problem statement",
        field: "textarea",
        name: "problem",
        required: true,
      },
      {
        label: "Choose programming language",
        field: "dropdown",
        name: "language",
        options: ["JavaScript", "Python", "Java", "C++", "Go", "Ruby"],
        required: true,
      },
    ],
  },
  {
    name: "Regex Pattern Generator",
    desc: "Generate regular expressions based on your input criteria.",
    category: "Coding",
    icon: "https://cdn-icons-png.flaticon.com/128/2907/2907761.png",
    aiPrompt:
      "Generate a regular expression (regex) based on the given pattern description.",
    slug: "regex-generator",
    form: [
      {
        label: "Describe the pattern",
        field: "textarea",
        name: "pattern",
        required: true,
      },
    ],
  },

  // Fun & Miscellaneous Tools
  {
    name: "Add Emojis to Text",
    desc: "Enhance your text by automatically adding relevant emojis.",
    category: "Writing",
    icon: "https://cdn-icons-png.flaticon.com/128/616/616489.png",
    aiPrompt:
      "Add relevant emojis to the given text while keeping the meaning intact.",
    slug: "add-emojis-to-text",
    form: [
      {
        label: "Enter your text",
        field: "textarea",
        name: "text",
        required: true,
      },
    ],
  },
  {
    name: "Social Media Post Generator",
    desc: "Generate engaging social media post content for various platforms.",
    category: "Marketing",
    icon: "https://cdn-icons-png.flaticon.com/128/733/733579.png",
    aiPrompt:
      "Generate a social media post for the given platform and topic. Ensure it is engaging and concise.",
    slug: "social-media-post",
    form: [
      {
        label: "Choose platform",
        field: "dropdown",
        name: "platform",
        options: ["Twitter", "Facebook", "Instagram", "LinkedIn"],
        required: true,
      },
      {
        label: "Enter topic or message",
        field: "textarea",
        name: "message",
        required: true,
      },
    ],
  },
  {
    name: "Catchy Product Name Generator",
    desc: "Generate unique and catchy names for your product or brand.",
    category: "Business",
    icon: "https://cdn-icons-png.flaticon.com/128/2748/2748558.png",
    aiPrompt:
      "Generate 5 unique and catchy product names based on the given industry and keywords.",
    slug: "product-name-generator",
    form: [
      {
        label: "Enter industry",
        field: "input",
        name: "industry",
        required: true,
      },
      { label: "Enter keywords", field: "input", name: "keywords" },
    ],
  },
  {
    name: "Email Tone Adjuster",
    desc: "Modify the tone of your email to be more professional, friendly, or diplomatic.",
    category: "Writing",
    icon: "https://cdn-icons-png.flaticon.com/128/5071/5071606.png",
    aiPrompt:
      "Rewrite the given email text to adjust its tone while maintaining the original message.",
    slug: "email-tone-adjuster",
    form: [
      {
        label: "Paste your email text",
        field: "textarea",
        name: "emailText",
        required: true,
      },
      {
        label: "Select desired tone",
        field: "dropdown",
        name: "tone",
        options: [
          "Professional",
          "Friendly",
          "Diplomatic",
          "Assertive",
          "Empathetic",
        ],
        required: true,
      },
    ],
  },
  {
    name: "Travel Itinerary Planner",
    desc: "Generate personalized travel itineraries based on your preferences and constraints.",
    category: "Travel",
    icon: "https://cdn-icons-png.flaticon.com/128/3050/3050451.png",
    aiPrompt:
      "Create a detailed travel itinerary based on the destination, duration, budget, and interests.",
    slug: "travel-itinerary-generator",
    form: [
      {
        label: "Destination",
        field: "input",
        name: "destination",
        required: true,
      },
      {
        label: "Trip duration (days)",
        field: "input",
        name: "duration",
        required: true,
      },
      {
        label: "Budget range",
        field: "dropdown",
        name: "budget",
        options: ["Budget", "Mid-range", "Luxury"],
        required: true,
      },
      {
        label: "Interests",
        field: "input",
        name: "interests",
        placeholder: "e.g., history, food, adventure",
      },
    ],
  },
  {
    name: "Interview Question Generator",
    desc: "Create tailored interview questions for specific job roles and industries.",
    category: "Career",
    icon: "https://cdn-icons-png.flaticon.com/128/8033/8033840.png",
    aiPrompt:
      "Generate a comprehensive list of interview questions for the specified job role and industry.",
    slug: "interview-question-generator",
    form: [
      {
        label: "Job Role",
        field: "input",
        name: "jobRole",
        required: true,
      },
      {
        label: "Industry",
        field: "input",
        name: "industry",
        required: true,
      },
      {
        label: "Experience Level",
        field: "dropdown",
        name: "experience",
        options: ["Entry-level", "Mid-level", "Senior", "Executive"],
        required: true,
      },
    ],
  },
  {
    name: "Habit Tracker Motivation Generator",
    desc: "Create personalized motivational messages and strategies for maintaining habits.",
    category: "Productivity",
    icon: "https://cdn-icons-png.flaticon.com/128/3050/3050525.png",
    aiPrompt:
      "Generate personalized motivation and strategy suggestions for maintaining a specific habit.",
    slug: "habit-motivation-generator",
    form: [
      {
        label: "Habit to track",
        field: "input",
        name: "habit",
        required: true,
      },
      {
        label: "Current challenge",
        field: "textarea",
        name: "challenge",
        placeholder: "What makes this habit difficult for you?",
      },
      {
        label: "Motivation type",
        field: "dropdown",
        name: "motivationType",
        options: ["Encouraging", "Tough Love", "Strategic", "Mindful"],
        required: true,
      },
    ],
  },
  {
    name: "Personal Finance Advice Generator",
    desc: "Generate personalized financial advice and saving strategies.",
    category: "Finance",
    icon: "https://cdn-icons-png.flaticon.com/128/2516/2516000.png",
    aiPrompt:
      "Provide tailored financial advice based on income, expenses, and financial goals.",
    slug: "personal-finance-advisor",
    form: [
      {
        label: "Monthly Income",
        field: "input",
        name: "income",
        required: true,
      },
      {
        label: "Monthly Expenses",
        field: "input",
        name: "expenses",
        required: true,
      },
      {
        label: "Financial Goal",
        field: "dropdown",
        name: "goal",
        options: [
          "Save for Emergency Fund",
          "Invest",
          "Reduce Debt",
          "Plan for Retirement",
        ],
        required: true,
      },
    ],
  },
  {
    name: "Love Poem Generator",
    desc: "Create personalized romantic poems for your spouse or partner.",
    category: "Writing",
    icon: "https://cdn-icons-png.flaticon.com/128/2356/2356891.png",
    aiPrompt:
      "Write a heartfelt, personalized love poem based on the provided details about your relationship.",
    slug: "romantic-poem-generator",
    form: [
      {
        label: "Your Partner's Name",
        field: "input",
        name: "partnerName",
        required: true,
      },
      {
        label: "Relationship Details",
        field: "textarea",
        name: "relationshipDetails",
        placeholder:
          "Special memories, qualities you love, moments you cherish",
      },
      {
        label: "Poem Style",
        field: "dropdown",
        name: "poemStyle",
        options: ["Romantic", "Passionate", "Tender", "Playful"],
        required: true,
      },
    ],
  },
  {
    name: "Birthday Invitation Generator",
    desc: "Create personalized and creative birthday party invitations.",
    category: "Celebration",
    icon: "https://cdn-icons-png.flaticon.com/128/1909/1909226.png",
    aiPrompt:
      "Generate a unique and engaging birthday party invitation based on the provided details.",
    slug: "birthday-invitation-creator",
    form: [
      {
        label: "Birthday Person's Name",
        field: "input",
        name: "name",
        required: true,
      },
      {
        label: "Age/Milestone",
        field: "input",
        name: "age",
        required: true,
      },
      {
        label: "Party Theme",
        field: "input",
        name: "theme",
        placeholder: "Optional: e.g., Superhero, Tropical, Vintage",
      },
      {
        label: "Invitation Tone",
        field: "dropdown",
        name: "tone",
        options: ["Playful", "Elegant", "Humorous", "Exciting"],
        required: true,
      },
    ],
  },
  {
    name: "Retirement Hobby Recommender",
    desc: "Suggest personalized hobby ideas for retirees based on interests and abilities.",
    category: "Lifestyle",
    icon: "https://cdn-icons-png.flaticon.com/128/3003/3003035.png",
    aiPrompt:
      "Generate a list of engaging hobby suggestions tailored to the retiree's interests, physical abilities, and preferences.",
    slug: "retirement-hobby-generator",
    form: [
      {
        label: "Previous Interests",
        field: "textarea",
        name: "previousInterests",
        placeholder: "Hobbies, work, skills from earlier life",
      },
      {
        label: "Physical Ability Level",
        field: "dropdown",
        name: "physicalAbility",
        options: ["Very Active", "Moderately Active", "Limited Mobility"],
        required: true,
      },
      {
        label: "Learning Preference",
        field: "dropdown",
        name: "learningStyle",
        options: ["Hands-on", "Digital", "Social", "Independent"],
        required: true,
      },
    ],
  },
  {
    name: "Emotional Healing Pathway",
    desc: "Generate personalized strategies for healing emotional traumas and building resilience.",
    category: "Mental Health",
    icon: "https://cdn-icons-png.flaticon.com/128/4205/4205840.png",
    aiPrompt:
      "Create a compassionate, step-by-step healing approach tailored to the described emotional challenges.",
    slug: "emotional-healing-guide",
    form: [
      {
        label: "Type of Emotional Challenge",
        field: "dropdown",
        name: "challengeType",
        options: [
          "Grief",
          "Relationship Trauma",
          "Work Stress",
          "Past Abuse",
          "Anxiety",
        ],
        required: true,
      },
      {
        label: "Brief Description",
        field: "textarea",
        name: "description",
        placeholder: "Share context about your emotional experience",
      },
      {
        label: "Support Preference",
        field: "dropdown",
        name: "supportStyle",
        options: [
          "Self-guided",
          "Professional Help",
          "Community Support",
          "Holistic Approach",
        ],
        required: true,
      },
    ],
  },
  {
    name: "Meditation Technique Finder",
    desc: "Discover personalized meditation techniques based on your goals and experience.",
    category: "Wellness",
    icon: "https://cdn-icons-png.flaticon.com/128/2503/2503508.png",
    aiPrompt:
      "Recommend specific meditation techniques aligned with the user's wellness objectives and meditation experience.",
    slug: "meditation-technique-generator",
    form: [
      {
        label: "Primary Goal",
        field: "dropdown",
        name: "meditationGoal",
        options: [
          "Stress Reduction",
          "Emotional Balance",
          "Spiritual Growth",
          "Mindfulness",
          "Better Sleep",
        ],
        required: true,
      },
      {
        label: "Meditation Experience",
        field: "dropdown",
        name: "experienceLevel",
        options: ["Beginner", "Intermediate", "Advanced"],
        required: true,
      },
      {
        label: "Time Available",
        field: "dropdown",
        name: "timeCommitment",
        options: ["5-10 minutes", "15-20 minutes", "30+ minutes"],
        required: true,
      },
    ],
  },
  {
    name: "Story Contents Page Generator",
    desc: "Create a structured contents page for your book or story based on your plot outline.",
    category: "Writing",
    icon: "https://cdn-icons-png.flaticon.com/128/3465/3465449.png",
    aiPrompt:
      "Generate a comprehensive and engaging contents page that captures the essence of the story's narrative structure.",
    slug: "story-contents-generator",
    form: [
      {
        label: "Story Genre",
        field: "dropdown",
        name: "genre",
        options: [
          "Fiction",
          "Non-fiction",
          "Fantasy",
          "Mystery",
          "Science Fiction",
          "Memoir",
        ],
        required: true,
      },
      {
        label: "Plot Outline",
        field: "textarea",
        name: "plotOutline",
        placeholder:
          "Provide a brief overview of your story's main plot points and narrative arc",
      },
      {
        label: "Preferred Chapter Style",
        field: "dropdown",
        name: "chapterStyle",
        options: ["Numbered", "Named", "Themed"],
        required: true,
      },
    ],
  },
  {
    name: "Personal Counseling Insights",
    desc: "Generate personalized counseling advice and coping strategies.",
    category: "Mental Health",
    icon: "https://cdn-icons-png.flaticon.com/128/4320/4320347.png",
    aiPrompt:
      "Provide compassionate, professional counseling insights tailored to the described emotional challenge.",
    slug: "counseling-advice-generator",
    form: [
      {
        label: "Emotional Challenge",
        field: "dropdown",
        name: "challengeType",
        options: [
          "Relationship Issues",
          "Anxiety",
          "Depression",
          "Self-Esteem",
          "Life Transition",
        ],
        required: true,
      },
      {
        label: "Personal Context",
        field: "textarea",
        name: "context",
        placeholder: "Brief description of your current situation",
      },
      {
        label: "Support Approach",
        field: "dropdown",
        name: "supportStyle",
        options: [
          "Empathetic Listening",
          "Practical Strategies",
          "Emotional Validation",
          "Goal-Oriented",
        ],
        required: true,
      },
    ],
  },
  {
    name: "Stress Management Toolkit",
    desc: "Create personalized strategies to manage and reduce stress.",
    category: "Wellness",
    icon: "https://cdn-icons-png.flaticon.com/128/1022/1022656.png",
    aiPrompt:
      "Develop a comprehensive stress management plan tailored to the user's specific stressors and lifestyle.",
    slug: "stress-management-generator",
    form: [
      {
        label: "Primary Stress Source",
        field: "dropdown",
        name: "stressSource",
        options: [
          "Work",
          "Personal Relationships",
          "Financial",
          "Health",
          "Time Management",
        ],
        required: true,
      },
      {
        label: "Stress Intensity",
        field: "dropdown",
        name: "stressLevel",
        options: ["Mild", "Moderate", "Severe"],
        required: true,
      },
      {
        label: "Available Time for Stress Management",
        field: "dropdown",
        name: "timeCommitment",
        options: [
          "5-15 minutes daily",
          "15-30 minutes daily",
          "30+ minutes daily",
        ],
        required: true,
      },
    ],
  },
];
